# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'button1.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import sys
import math
import SPproj
class Ui_Dialog1(object):
     
        def open(self):
            self.input1 = float(self.lineEdit.text())
            self.input2 = float(self.lineEdit_2.text())
    #        self.calculate = QtGui.QPushButton('Calculate', self)
    #        self.calculate.clicked.connect(self.handleCalculate)
    #        layout = QtGui.QHBoxLayout(self)
    #        layout.addWidget(self.input1)
    #        layout.addWidget(self.calculate)
    #       
            row = float(self.input1 / self.input2)
            ls = (row) / (1 - row)
            wq = self.input1 * ls
            ws = row * wq
            lq = ls * row
            lq = round(lq, 3)
            ls = round(ls, 3)
            ws = round(ws, 3)
            wq = round(wq, 3)
            ls = str(ls)
            lq = str(lq)
            wq = str(wq)
            ws= str(ws)
            self.lineEdit_8.insert(lq)
            self.lineEdit_5.insert(ls)
            self.lineEdit_7.insert(wq)
            self.lineEdit_6.insert(ws)
    #    def lambda(self):
    #        lam = int(self.lineEdit.getText())
    #    
    #    def mu(self):
    #        mu = int(self.lineEdit2)
        def goBack(self):
            self.window = QtWidgets.QMainWindow()
            self.ui = SPproj.Ui_Dialog()
            self.ui.setupUi(self.window)
            self.window.show()
            
        def setupUi(self, Dialog):
            Dialog.setObjectName("Dialog")
            Dialog.resize(1821, 956)
            Dialog.setAccessibleName("")
            Dialog.setAccessibleDescription("")
            self.label = QtWidgets.QLabel(Dialog)
            self.label.setGeometry(QtCore.QRect(150, 150, 121, 71))
            font = QtGui.QFont()
            font.setPointSize(20)
            self.label.setFont(font)
            self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
            self.label.setObjectName("label")
            self.label_2 = QtWidgets.QLabel(Dialog)
            self.label_2.setGeometry(QtCore.QRect(1100, 150, 121, 71))
            font = QtGui.QFont()
            font.setPointSize(20)
            self.label_2.setFont(font)
            self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
            self.label_2.setObjectName("label_2")
            self.label_3 = QtWidgets.QLabel(Dialog)
            self.label_3.setGeometry(QtCore.QRect(440, 10, 811, 81))
            font = QtGui.QFont()
            font.setPointSize(17)
            font.setBold(True)
            font.setWeight(75)
            self.label_3.setFont(font)
            self.label_3.setAlignment(QtCore.Qt.AlignCenter)
            self.label_3.setObjectName("label_3")
            self.pushButton = QtWidgets.QPushButton(Dialog)
            self.pushButton.setGeometry(QtCore.QRect(710, 290, 411, 121))
            font = QtGui.QFont()
            font.setPointSize(18)
            font.setBold(False)
            font.setItalic(False)
            font.setUnderline(False)
            font.setWeight(50)
            self.pushButton.setFont(font)
            self.pushButton.setObjectName("pushButton")
            self.pushButton.clicked.connect(self.open)
            self.label_4 = QtWidgets.QLabel(Dialog)
            self.label_4.setGeometry(QtCore.QRect(200, 480, 161, 61))
            font = QtGui.QFont()
            font.setPointSize(14)
            font.setBold(True)
            font.setWeight(75)
            self.label_4.setFont(font)
            self.label_4.setAlignment(QtCore.Qt.AlignCenter)
            self.label_4.setObjectName("label_4")
            self.label_5 = QtWidgets.QLabel(Dialog)
            self.label_5.setGeometry(QtCore.QRect(210, 650, 161, 61))
            font = QtGui.QFont()
            font.setPointSize(14)
            font.setBold(True)
            font.setWeight(75)
            self.label_5.setFont(font)
            self.label_5.setAlignment(QtCore.Qt.AlignCenter)
            self.label_5.setObjectName("label_5")
            self.label_6 = QtWidgets.QLabel(Dialog)
            self.label_6.setGeometry(QtCore.QRect(1230, 640, 161, 61))
            font = QtGui.QFont()
            font.setPointSize(14)
            font.setBold(True)
            font.setWeight(75)
            self.label_6.setFont(font)
            self.label_6.setAlignment(QtCore.Qt.AlignCenter)
            self.label_6.setObjectName("label_6")
            self.label_7 = QtWidgets.QLabel(Dialog)
            self.label_7.setGeometry(QtCore.QRect(1230, 470, 161, 61))
            font = QtGui.QFont()
            font.setPointSize(14)
            font.setBold(True)
            font.setWeight(75)
            self.label_7.setFont(font)
            self.label_7.setAlignment(QtCore.Qt.AlignCenter)
            self.label_7.setObjectName("label_7")
            self.lineEdit = QtWidgets.QLineEdit(Dialog)
            self.lineEdit.setGeometry(QtCore.QRect(310, 140, 321, 101))
            font = QtGui.QFont()
            font.setPointSize(18)
            font.setBold(True)
            font.setWeight(75)
            self.lineEdit.setFont(font)
            self.lineEdit.setText("")
            self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
            self.lineEdit.setObjectName("lineEdit")
            self.lineEdit_2 = QtWidgets.QLineEdit(Dialog)
            self.lineEdit_2.setGeometry(QtCore.QRect(1260, 140, 321, 101))
            font = QtGui.QFont()
            font.setPointSize(18)
            font.setBold(True)
            font.setWeight(75)
            self.lineEdit_2.setFont(font)
            self.lineEdit_2.setText("")
            self.lineEdit_2.setAlignment(QtCore.Qt.AlignCenter)
            self.lineEdit_2.setObjectName("lineEdit_2")
            self.lineEdit_5 = QtWidgets.QLineEdit(Dialog)
            self.lineEdit_5.setGeometry(QtCore.QRect(1390, 450, 141, 101))
            font = QtGui.QFont()
            font.setPointSize(18)
            font.setBold(True)
            font.setWeight(75)
            self.lineEdit_5.setFont(font)
            self.lineEdit_5.setText("")
            self.lineEdit_5.setAlignment(QtCore.Qt.AlignCenter)
            self.lineEdit_5.setObjectName("lineEdit_5")
            self.lineEdit_6 = QtWidgets.QLineEdit(Dialog)
            self.lineEdit_6.setGeometry(QtCore.QRect(1390, 620, 141, 101))
            font = QtGui.QFont()
            font.setPointSize(18)
            font.setBold(True)
            font.setWeight(75)
            self.lineEdit_6.setFont(font)
            self.lineEdit_6.setText("")
            self.lineEdit_6.setAlignment(QtCore.Qt.AlignCenter)
            self.lineEdit_6.setObjectName("lineEdit_6")
            self.lineEdit_7 = QtWidgets.QLineEdit(Dialog)
            self.lineEdit_7.setGeometry(QtCore.QRect(370, 630, 141, 101))
            font = QtGui.QFont()
            font.setPointSize(18)
            font.setBold(True)
            font.setWeight(75)
            self.lineEdit_7.setFont(font)
            self.lineEdit_7.setText("")
            self.lineEdit_7.setAlignment(QtCore.Qt.AlignCenter)
            self.lineEdit_7.setObjectName("lineEdit_7")
            self.lineEdit_8 = QtWidgets.QLineEdit(Dialog)
            self.lineEdit_8.setGeometry(QtCore.QRect(370, 460, 141, 101))
            font = QtGui.QFont()
            font.setPointSize(18)
            font.setBold(True)
            font.setWeight(75)
            self.lineEdit_8.setFont(font)
            self.lineEdit_8.setText("")
            self.lineEdit_8.setAlignment(QtCore.Qt.AlignCenter)
            self.lineEdit_8.setObjectName("lineEdit_8")
            self.pushButton_2 = QtWidgets.QPushButton(Dialog)
            self.pushButton_2.setGeometry(QtCore.QRect(760, 540, 311, 91))
            font = QtGui.QFont()
            font.setPointSize(18)
            font.setBold(False)
            font.setItalic(False)
            font.setUnderline(False)
            font.setWeight(50)
            self.pushButton_2.setFont(font)
            self.pushButton_2.setObjectName("pushButton_2")
            self.pushButton_2.clicked.connect(self.goBack)
            self.retranslateUi(Dialog)
            QtCore.QMetaObject.connectSlotsByName(Dialog)

        def retranslateUi(self, Dialog):
            _translate = QtCore.QCoreApplication.translate
            Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
            self.label.setText(_translate("Dialog", "λ ="))
            self.label_2.setText(_translate("Dialog", "μ ="))
            self.label_3.setText(_translate("Dialog", "Model 1: (M/M/1) (GD/∞/∞)"))
            self.pushButton.setText(_translate("Dialog", "Calculate!"))
            self.label_4.setText(_translate("Dialog", "Lq"))
            self.label_5.setText(_translate("Dialog", "Wq"))
            self.label_6.setText(_translate("Dialog", "Ws"))
            self.label_7.setText(_translate("Dialog", "Ls"))
            self.pushButton_2.setText(_translate("Dialog", "Go Back"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog1()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

